defaults:
  - _self_
  - task/tokenizer: libero/libero10

name: train_questtok
_target_: oat.workspace.train_questtok.TrainQueSTTokWorkspace

seed: 42
horizon: 32
task_name: ${task.tokenizer.name}
action_dim: ${task.tokenizer.shape_meta.action.shape[0]}

tokenizer: 
  _target_: oat.tokenizer.quest.tokenizer.QueSTTok
  # action chunk related params
  action_dim: ${action_dim}
  horizon: ${horizon}
  # model related params
  encoder_dim: 256
  encoder_nhead: 4
  encoder_nlayer: 2
  use_causal_encoder: true
  decoder_dim: 256
  decoder_nhead: 4
  decoder_nlayer: 4
  use_causal_decoder: true
  downsample_factor: 4
  dropout: 0.1
  # vector-quantization related params
  vq_type: fsq
  fsq_level: [8, 5, 5, 5]
  vq_codebook_size: 1024
  vq_codebook_dim: 512

training:
  resume: True
  allow_bf16: True
  max_grad_norm: 1.0
  num_epochs: 5001
  checkpoint_every: 10
  val_every: 10
  sample_every: 10
  lr_scheduler: constant
  lr_warmup_steps: 100
  gradient_accumulate_every: 1
  max_train_steps: null
  max_val_steps: null
  max_reconst_steps: null
  seed: ${seed}
  use_ema: True
  num_demo: 500
  tqdm_interval_sec: 1.0

ema:
  _target_: oat.model.diffusion.ema_model.EMAModel
  update_after_step: 0
  inv_gamma: 1.0
  power: 0.75
  min_value: 0.0
  max_value: 0.9999

optimizer:
  learning_rate: 5.0e-5
  weight_decay: 0.0
  betas: [0.9, 0.95]
  
dataloader:
  batch_size: 256
  num_workers: 4
  shuffle: True
  pin_memory: True
  persistent_workers: True
  drop_last: True

val_dataloader:
  batch_size: 256
  num_workers: 4
  shuffle: False
  pin_memory: True
  persistent_workers: True
  drop_last: True

logging:
  project: oat_dev
  resume: True
  mode: online
  name: ${now:%Y%m%d.%H%M%S}_${name}_${task_name}_N${training.num_demo}
  tags: ["${name}", "${task_name}"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: test_reconst_mse
    mode: min
    k: 3
    format_str: 'ep-{epoch:04d}_mse-{test_reconst_mse:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False

multi_run:
  run_dir: output/${now:%Y%m%d}/${now:%H%M%S}_${name}_${task_name}_N${training.num_demo}
  wandb_name_base: ${now:%Y%m%d.%H%M%S}_${name}_${task_name}_N${training.num_demo}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: output/${now:%Y%m%d}/${now:%H%M%S}_${name}_${task_name}_N${training.num_demo}
  sweep:
    dir: output/${now:%Y%m%d}/${now:%H%M%S}_${name}_${task_name}_N${training.num_demo}
    subdir: ${hydra.job.num}
