name: libero10

task_name: libero10

shape_meta: &shape_meta
  action:
    shape: [7]


dataset:
  _target_: oat.dataset.zarr_dataset.ZarrDataset
  zarr_path: data/libero/libero10_N${training.num_demo}.zarr
  obs_keys: []
  action_key: action
  n_obs_steps: 0
  n_action_steps: ${horizon}
  seed: ${seed}
  val_ratio: 0.1
  